# Generated by Django 2.2.5 on 2022-10-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210226_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='communitication',
            new_name='communication',
        ),
    ]
