# Generated by Django 2.2.5 on 2022-10-09 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20210226_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.OneToOneField(on_delete=True, related_name='list', to=settings.AUTH_USER_MODEL),
        ),
    ]
